networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - elasticsearch
      - tempo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    networks:
      - monitoring
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
  
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    networks:
      - monitoring
    command: "-target=distributor -config.file=/etc/tempo.yml"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "4319:4318"   # tempo
      - "3200:3200"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    networks:
      - monitoring
    ports:
      - "4317:4317"   # OTLP gRPC (default)
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./otel-config.yml:/etc/otel/config.yaml
    depends_on:
      - prometheus
      - elasticsearch
      - tempo

