receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
  logging:
    logLevel: info
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
  tempo:
    endpoint: "http://tempo:3200"

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
