services:
  postgres:
    container_name: docker-postgres
    image: postgres:latest
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - local-network-service

volumes:
  postgres-data:

networks:
  local-network-service:
    external: false
    name: local-network-service
