version: '3.8'
services:
  postgres:
    container_name: bri-relawan-pg
    image: postgres
    hostname: localhost
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - local-network-service

  pgadmin:
    container_name: bri-relawan-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    networks:
      - local-network-service

volumes:
  postgres-data:


networks:
  local-network-service:
    external: false
    name: local-network-service
