services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    networks:
        - redis-conn
  redis-insight:
    image: redis/redisinsight:latest
    ports:
    - 5540:5540
    networks:
        - redis-conn

networks:
  redis-conn:
    external: false
    name: redis-conn