apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name: redis-insight
        image: redis/redisinsight:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5540
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
spec:
  selector:
    app: redis-insight
  ports:
    - protocol: TCP
      port: 5540
      targetPort: 5540